title: FCLI
description: > # this means to ignore newlines until "baseurl:"
  FCLI (fcli) is a universal command line program for interacting with all Fortify application security testing products and more.

baseurl: "/fcli"
url: "https://fortify-ps.github.io"

defaults:
  - scope:
      path: "dev_*/fcli.html"
    values:
      manpage_dev: true
  - scope:
      path: "v*/fcli.html"
    values:
      manpage_release: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

### content configuration ###
keywords:    "Fortify, FCLI, CLI"
source_link: "/fcli"
highlighter: rouge

kramdown:
  auto_ids:  true
  

