name: Build and release
on:
  push:
    branches:
      - '**'
       
env:
  native_image_opts: --verbose -H:Log=registerResource:verbose
          
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check-out source code
        uses: actions/checkout@v3

      - name: PROD - Prepare GitHub release
        id: create_prod_release
        uses: GoogleCloudPlatform/release-please-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          command: github-release
          release-type: simple
          package-name: ${{ github.event.repository.name }}  
          
      - name: PROD - Define release info
        if: steps.create_prod_release.outputs.release_created
        run: |
          tag=${{steps.create_prod_release.outputs.tag_name}}
          version=${{steps.create_prod_release.outputs.version}}
          major=${{steps.create_prod_release.outputs.major}}
          minor=${{steps.create_prod_release.outputs.minor}}
          patch=${{steps.create_prod_release.outputs.patch}}  
          echo DO_BUILD=true >> $GITHUB_ENV
          echo DO_RELEASE=true >> $GITHUB_ENV
          echo DO_PROD_RELEASE=true >> $GITHUB_ENV
          echo RELEASE_TAG=${tag} >> $GITHUB_ENV
          echo RELEASE_VERSION=${version} >> $GITHUB_ENV
          
      - name: DEV - Define release info
        if: startsWith(github.ref, 'refs/heads/') && !env.DO_PROD_RELEASE
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          tag="dev_${branch//[^a-zA-Z0-9_.-]/.}" # Replace all special characters by a dot
          version="0.$(date +'%Y%m%d.%H%M%S')-${tag}"
          echo DO_BUILD=true >> $GITHUB_ENV # We always want to do a build if we're building a branch
          echo BRANCH=${branch} >> $GITHUB_ENV
          echo RELEASE_TAG=${tag} >> $GITHUB_ENV
          echo RELEASE_VERSION=${version} >> $GITHUB_ENV
          
          if git ls-remote --exit-code origin refs/tags/${tag} >/dev/null 2>&1; then
            echo "Found tag ${tag}, development release will be published"
            echo DO_RELEASE=true >> $GITHUB_ENV
            echo DO_DEV_RELEASE=true >> $GITHUB_ENV
          else 
            echo "Tag ${tag} does not exist, no development release will be published"
          fi 
      
      - name: Build release ${{env.RELEASE_VERSION}}
        if: env.DO_BUILD
        run: ./gradlew clean build dist distThirdParty -Pversion=${{env.RELEASE_VERSION}}
        
      - name: Check fcli version
        if: env.DO_BUILD
        run: java -jar build/libs/fcli.jar --version | tee /dev/stderr | grep -E '[0-9]+\.[0-9]+\.[0-9]+' >/dev/null || (echo "fcli --version doesn't output proper version number"; exit 1)
        
      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/dist/*
          
    outputs:
      do_release: ${{ env.DO_RELEASE }}
      do_dev_release: ${{ env.DO_DEV_RELEASE }}
      release_tag: ${{ env.RELEASE_TAG }}
        
  release:
    name: release
    if: needs.build.outputs.do_release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check-out source code
        uses: actions/checkout@v3
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./
          
      - name: Remove fcli_completion script
        run: rm -f artifact/fcli_completion
          
      - name: PROD - Prepare release PR
        if: github.ref == 'refs/heads/main'
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          command: release-pr
          release-type: simple
          package-name: ${{ github.event.repository.name }}
          
      - name: DEV - Prepare GitHub release 
        if: needs.build.outputs.do_dev_release
        run: |
          gh release delete ${{ needs.build.outputs.release_tag }} -y || true
          gh release create ${{ needs.build.outputs.release_tag }} -p -t "Development Release - ${GITHUB_REF#refs/heads/} branch" -n 'See `Assets` section below for latest build artifacts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: DEV - Update ${{ needs.build.outputs.release_tag }} tag
        uses: richardsimko/update-tag@v1
        if: needs.build.outputs.do_dev_release
        with:
          tag_name: ${{ needs.build.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Upload assets to release
        if: needs.build.outputs.do_release
        run: |
          files=$(find "./artifact" -type f -printf "%p ")
          gh release upload "${{ needs.build.outputs.release_tag }}" $files --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
  publishPages:
    name: publishPages
    if: needs.build.outputs.do_release
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:
      - name: Check-out existing docs from gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: docs
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./
          
      - name: Update documentation from artifact
        run: |
          # Delete all Git-related files
          rm -rf docs/.git*
          
          # Define the output directory, based on tag/branch name
          dir=docs/${{ needs.build.outputs.release_tag }}
          
          # Delete, recreate and fill the directory for the current tag/branch name,
          # while leaving documentation for other tags/branches intact (as checked out above)
          rm -rf "${dir}"
          mkdir -p "${dir}"
          unzip artifact/docs-jekyll.zip -d "${dir}"
          
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true
          
          
  cleanup:
    name: cleanup
    if: needs.build.outputs.do_release 
    needs: [release, publishPages] 
    runs-on: ubuntu-latest 
    steps:
      - name: Delete artifacts if uploaded to release
        uses: geekyeggo/delete-artifact@v1
        with:
          name: artifact
          failOnError: false   
